componentEntries:
  MONITOR:
    attributeOrder: ["SIZE", "RESOLUTION", "GLARE", "OUTPUT", "BODY", "BRIGHTNESS", "RESPONSE_TIME", "REFRESH_RATE"]
    attributeEntries:
      RESPONSE_TIME:
        1:
          word: TOKEN
          condition: CONTAINS
          value: "MS|milliseconds"
          qualifiedActions:
            - TOKEN_TRIM_MATCH
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_ITERATION
        2: 
          word: TOKEN
          condition: IN_BETWEEN_EXCLUSIVE
          value: "0,50"
          qualifiedActions:
            - TOKEN_APPEND_END("ms")
            - TOKEN_SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS("6")