componentEntries:
  MONITOR:
    attributeOrder: ["SIZE", "RESOLUTION", "GLARE", "OUTPUT", "BODY", "BRIGHTNESS", "RESPONSE_TIME", "REFRESH_RATE"]
    attributeEntries:
      RESPONSE_TIME:
        1:
          location: "END"
          condition: "CONTAINS"
          value: "MS|milliseconds"
          qualifiedActions:
            - "Continue"
          unqualifiedActions:
            - "ExitToNextWordIteration"
        2: 
          location: "REST"
          condition: "IS-A"
          value: "DOUBLE|INTEGER"
          qualifiedActions:
            - "Continue"
          unqualifiedActions:
            - "AppendNearbyCharactersFromNextOrPriorWordAndRetry(max of 6 appends before breaking and going to next word iteration)"
        3:
          location: "REST"
          condition: "INBETWEEN_EXC"
          value: "0,50"
          qualifiedActions:
            - "Ship(\"REST\".append(MS))"
            - "ExitToNextWordIteration"
          unqualifiedActions:
            - "AppendNearbyCharactersFromNextOrPriorWordAndRetry(max of 6 appends before breaking and going to next word iteration)"
