componentEntries:
  MONITOR:
    attributeOrder: ["SIZE", "RESOLUTION", "GLARE", "OUTPUT", "BODY", "BRIGHTNESS", "RESPONSE_TIME", "REFRESH_RATE"]
    attributeEntries:
      RESPONSE_TIME:
        1:
          location: END
          condition: CONTAINS
          value: "MS|milliseconds"
          qualifiedActions:
            - TRIM_TOKEN
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        2: 
          location: WHOLE
          condition: IN_BETWEEN_EXCLUSIVE
          value: "0,50"
          qualifiedActions:
            - APPEND_END("ms")
            - SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS(6)