componentEntries:
  '1':
    name: "MONITOR"
    attributes: "company model size resolution refreshRate responseTime panelTech"
    commands:
      - "ex1"
      - "ex2"
  '2':
    name: "GPU"
    attributes: "company model ramCapacity ramSpeed"
    commands:
      - "ex4"
      - "ex3"