# PreProcessIt v0.1.6-beta by @tbm00
# https://github.com/tbm00/PreProcessIt

concurrentThreading: true
threadPoolSizeOverride: -1

components:
  MONITOR:
    inputLineRules:
      "1":
        word: WORKING_LINE
        condition: STARTS_WITH
        value: "EXAMPLE"
        qualifiedActions:
          - TRIM_MATCH_FIRST
          - SHIP
          - EXIT_TO_NEXT_LINE_ITERATION
        unqualifiedActions:
          - EXIT_TO_NEXT_LINE_ITERATION
    outputLineRules:
      "1":
        word: WORKING_LINE
        condition: NOT_IS_EMPTY
        value: ""
        qualifiedActions:
          - SET_CASING(upper)
          - PREPEND(",")
          - PREPEND($INITIAL_LINE_COPY$)
          - APPEND(",")
          - APPEND($LEFTOVERS$)
          - SHIP
          - EXIT_TO_NEXT_LINE_ITERATION
        unqualifiedActions:
          - EXIT_TO_NEXT_LINE_ITERATION
    attributeOutputOrder: ["RESPONSE_TIME", "REFRESH_RATE"]
    attributeOutputDelimiter: ","
    attributes:
      RESPONSE_TIME:
        "1":
          word: WORKING_TOKEN
          condition: CONTAINS
          value: "MS|milliseconds"
          qualifiedActions:
            - TRIM_MATCH_ALL
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: WORKING_TOKEN
          condition: IS_EMPTY
          value: ""
          qualifiedActions:
            - CONTINUE
          unqualifiedActions:
            - CONTINUE_AND_SKIP_NEXT_QUALIFIER
        "3": 
          word: LEFT_NEIGHBOR
          condition: IN_BETWEEN_INCLUSIVE
          value: "0,50"
          qualifiedActions:
            - TRIM_MATCH_FROM_LEFT_NEIGHBOR
            - FORMAT_NUMBER(#.#,false)
            - APPEND("ms")
            - DECLARE_TOKEN_PROCESSED
            - SHIP
            - EXIT_TO_NEXT_ATTRIBUTE_ITERATION
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "4": 
          word: WORKING_TOKEN
          condition: IN_BETWEEN_INCLUSIVE
          value: "0,50"
          qualifiedActions:
            - FORMAT_NUMBER(#.#,false)
            - APPEND("ms")
            - DECLARE_TOKEN_PROCESSED
            - SHIP
            - EXIT_TO_NEXT_ATTRIBUTE_ITERATION
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
      REFRESH_RATE:
        "1":
          word: WORKING_TOKEN
          condition: CONTAINS
          value: "HZ|hertz"
          qualifiedActions:
            - TRIM_MATCH_ALL
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: WORKING_TOKEN
          condition: IS_EMPTY
          value: ""
          qualifiedActions:
            - CONTINUE
          unqualifiedActions:
            - CONTINUE_AND_SKIP_NEXT_QUALIFIER
        "3": 
          word: LEFT_NEIGHBOR
          condition: IN_BETWEEN_INCLUSIVE
          value: "59,361"
          qualifiedActions:
            - TRIM_MATCH_FROM_LEFT_NEIGHBOR
            - APPEND("hz")
            - DECLARE_TOKEN_PROCESSED
            - SHIP
            - EXIT_TO_NEXT_ATTRIBUTE_ITERATION
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "4": 
          word: WORKING_TOKEN
          condition: IN_BETWEEN_INCLUSIVE
          value: "59,361"
          qualifiedActions:
            - APPEND("hz")
            - DECLARE_TOKEN_PROCESSED
            - SHIP
            - EXIT_TO_NEXT_ATTRIBUTE_ITERATION
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION