componentEntries:
  MONITOR:
    attributeOrder: ["RESPONSE_TIME", "REFRESH_RATE"]
    attributeEntries:
      RESPONSE_TIME:
        "1":
          word: TOKEN
          condition: CONTAINS
          value: "MS|milliseconds"
          qualifiedActions:
            - TRIM_MATCH_ALL
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: TOKEN
          condition: IN_BETWEEN_INCLUSIVE
          value: "0,50"
          qualifiedActions:
            - APPEND("ms")
            - SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS("6")
      REFRESH_RATE:
        "1":
          word: TOKEN
          condition: CONTAINS
          value: "HZ|hertz"
          qualifiedActions:
            - TRIM_MATCH_FROM_END
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: TOKEN
          condition: IN_BETWEEN_INCLUSIVE
          value: "59,361"
          qualifiedActions:
            - APPEND("hz")
            - SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS("6")