componentEntries:
  MONITOR:
    attributeOrder: ["RESPONSE_TIME", "REFRESH_RATE"]
    attributeEntries:
      RESPONSE_TIME:
        "1":
          word: TOKEN
          condition: CONTAINS
          value: "MS|milliseconds"
          qualifiedActions:
            - TOKEN_TRIM_MATCH
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: TOKEN
          condition: IN_BETWEEN_EXCLUSIVE
          value: "0,50"
          qualifiedActions:
            - TOKEN_APPEND("ms")
            - TOKEN_SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS("6")
      REFRESH_RATE:
        "1":
          word: TOKEN
          condition: CONTAINS
          value: "HZ|hertz"
          qualifiedActions:
            - TOKEN_TRIM_MATCH
            - CONTINUE
          unqualifiedActions:
            - EXIT_TO_NEXT_TOKEN_ITERATION
        "2": 
          word: TOKEN
          condition: IN_BETWEEN_EXCLUSIVE
          value: "59,361"
          qualifiedActions:
            - TOKEN_APPEND("hz")
            - TOKEN_SHIP
          unqualifiedActions:
            - TRY_NEIGHBORS("6")