name: Package and Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17.0.0+35

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Project Version
        id: get_version
        shell: bash
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Cache Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PreProcessIt-${{ runner.os }}
          path: |
            **/PreProcessIt-*.jar

      - name: Upload Release Jar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/PreProcessIt-${{ env.version }}.jar
          asset_name: PreProcessIt-${{ env.version }}.jar
          asset_content_type: application/java-archive